# Serve the pre-built React static files using Nginx
FROM nginx:1.26-alpine AS final

COPY admin-panel/dist /usr/share/nginx/html

# Copy custom Nginx configuration to support client-side React Routing redirection
COPY deployment/nginx.admin.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
